### ISSUE TITLE
Fatal Error when plugin is installed WP_Hooks not found

### ISSUE THREAD

**Issue by n8finch** [future-shop/wp-future-shop#13]
Hey @kopepasah I'm getting a fatal error when I try installing and activating the plugin on Pantheon and Strattic:

```
Fatal error: Uncaught Error: 
Class 'FutureShop\Helpers\WP\Hooks' not found in /var/strattic/site/public_html/wp-content/plugins/wp-future-shop/bootstrap.php:20 
Stack trace: 
#0 /var/strattic/site/public_html/wp-content/plugins/wp-future-shop/future-shop.php(93): FutureShop\Bootstrap->__construct('/var/strattic/s...') 
#1 /var/strattic/site/public_html/wp-admin/includes/plugin.php(2300): include('/var/strattic/s...') 
#2 /var/strattic/site/public_html/wp-admin/plugins.php(191): plugin_sandbox_scrape('wp-future-shop/...')
#3 {main} thrown in /var/strattic/site/public_html/wp-content/plugins/wp-future-shop/bootstrap.php on line 20
```

I was going to test and make sure the cart worked on both platforms. Anyway, wanted to note it here before moved on to something else, and see if you had any ideas, as I'm assuming it's an autoloading issue.

To reproduce:
1. zip the plugin files up and upload them via the wp-admin || SFTP the files up || deploy the files.
2. if uploaded, there should be a fatal error noted
3. if SFTP'd or deployed, try to activate the plugin, there should be a fatal error.

**Comment by kopepasah** [comment]
@n8finch assuming you included the `vendor` directory in your zip, correct?

**Comment by n8finch** [comment]
@kopepasah yep, zipped up or SFTP-ed everything, including vendor files.

**Comment by kopepasah** [comment]
@n8finch I believe this is resolved with this commit: https://github.com/future-shop/wp-future-shop/pull/12/commits/a6aef258eb41d6de6237f158c0a97495a23756d4

Please test and if everything looks good, let's merge the Cart into the `default` branch.

**Comment by n8finch** [comment]
@kopepasah made a couple extra changes to the shopping cart, looks like it works on Pantheon and Strattic static sites just fine.... Exciting!
