### ISSUE TITLE
REST API not responding

### ISSUE THREAD

**Issue by n8finch** [future-shop/wp-future-shop#25]
Go to: `/wp-json/stripe/v7/products` on a local install. 

Should see a list of products.

Instead, we see:
```
{
  code: "rest_forbidden",
  message: "Sorry, you are not allowed to do that.",
  data: {
    status: 401
  }
}
```

Might have been a bug with the permissions callback. Might need to change to `manage_options`.

**Comment by kopepasah** [comment]
Resolved.
